# Generated by Django 4.1.6 on 2023-02-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_rename_boyd_todo_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="sample"),
        ),
    ]
